language: python
python:
    - "2.7"
addons:
  postgresql: "9.4"
services:
    - postgresql
install: pip install -r requirements.txt
env:
  global:
    - TRAVIS_BUILD=true
script:
    - python manage.py upgrade
    - coverage run --source=blst --omit="*virtualenv*","*envs*","migrations/*","blst/__init__.py" manage.py test
branches:
  only:
      - master
      - develop
after_success:
    - coveralls
