language: python
python:
    - "2.7"
addons:
  postgresql: "9.4"
services:
    - postgresql
install: pip install -r requirements.txt
env:
  global:
    - TRAVIS_BUILD=true
before_script:
    - psql -c 'create database bucketlist;' -U postgres
script:
    - nosetests --with-coverage --cover-package=.
branches:
  only:
      - master
      - develop
after_success:
    - coveralls
