FORMAT: 1A
HOST: http://blst.herokuapp.com/

# BLST

**BLST** is a simple bucketlist API service allowing consumers to perform [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) operations on bucketlists as well as items in the respective bucketlits.

## bucketlists resource [/bucketlists/]

### Create a new bucketlist [POST]

You may create a bucketlist using this action. It takes a JSON
object containing a name for the bucketlist.

+ Request (application/json)

        { "name": "bucketlist-name" }

+ Response 201 (application/json)

    + Headers

            Location: /bucketlists/1
    + Body
    
            {
                "id": 1,
                "name": "bucketlist-name",
                "items": [],
                "date_created": "2016-01-07T10:36:33.434063",
                "date_modified": "2016-01-07T10:36:33.434077",
                "created_by": “123456”
            }
### View all bucketlists [GET]

You may view all the bucketlists you have created using this action.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "bucketlist-name",
                "items": [],
                "date_created": "2016-01-07T10:36:33.434063",
                "date_modified": "2016-01-07T10:36:33.434077",
                "created_by": “123456”
            },
            {
                "id": 2,
                "name": "second-bucketlist",
                "items": [
                    {
                        "id": 1,
                        "name": "I need to do X",
                        "date_created": "2016-01-07T10:50:50.535339",
                        "date_modified": "2016-01-07T10:50:50.525336",
                        "done": false
                    }
                ],
                "date_created": "2016-01-07T10:50:49.535345",
                "date_modified": "2016-01-07T10:50:49.535366",
                "created_by": “123456”
            }
        ]