"""empty message

Revision ID: a8f5b523c8c7
Revises: 8fa63f1a1e95
Create Date: 2016-01-21 14:01:19.536717

"""

# revision identifiers, used by Alembic.
revision = 'a8f5b523c8c7'
down_revision = '8fa63f1a1e95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logged_in', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'logged_in')
    ### end Alembic commands ###
